# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  composer-normalize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.3

      - run: composer install --no-interaction --no-progress --no-suggest

      - run: composer normalize

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Normalize composer.json

  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.3

      - run: composer install --no-interaction --no-progress --no-suggest

      - run: vendor/bin/php-cs-fixer fix --using-cache=no

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply php-cs-fixer changes
